name: Ghost Inspector Tests

on:
  push:
    branches: [main]
  


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: listar as suites
        uses: docker://ghostinspector/cli
        with: 
          args: suite list \
           --apiKey ${{ secrets.GI_API_KEY }} \
           --json

      - name: Executar testes do Ghost Inspector
        uses: docker://ghostinspector/cli
        with:
          args: suite execute 676331ba7a599a5bc8a55a83 \
            --apiKey ${{ secrets.GI_API_KEY }} \
            --startUrl https://staging.clint.digital \
            --errorOnFail

            