name: Ghost Inspector Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Ghost Inspector CLI e capturar saída
        run: |
          docker run ghostinspector/cli suite list --apiKey ${{ secrets.GI_API_KEY }} --json | jq '.[]._id' > output.json

      - name: Executar testes para cada ID extraído
        run: |
          errors=0
          
          for suite_id in $(cat output.json); do
            if [ "$suite_id" = "\"6761d7427a599a5bc844ad51\"" ]; then
              echo "Ignorando suíte ID: $suite_id"
              continue
            fi

            echo "Executando teste para a suíte ID: $suite_id"
            docker run ghostinspector/cli suite execute $suite_id \
              --apiKey ${{ secrets.GI_API_KEY }} \
              --startUrl ${{ vars.GI_START_URL }} || errors=$((errors+1)) 
          done  

          
          if [ $errors -gt 0 ]; then
            echo "$errors teste(s) falharam."
            exit 1  # Falha o workflow
          else
            echo "Todos os testes passaram!"
          fi 