name: Ghost Inspector Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Ghost Inspector CLI e capturar saída
        run: |
          docker run ghostinspector/cli suite list --apiKey ${{ secrets.GI_API_KEY }} --json | jq '.[]._id' > output.json

      - name: Executar testes para cada ID extraído
        run: |
          errors=0  # Inicializa a variável para contar falhas
          
          for suite_id in $(cat output.json); do
            echo "Executando teste para a suíte ID: $suite_id"
            docker run ghostinspector/cli suite execute $suite_id \
              --apiKey ${{ secrets.GI_API_KEY }} \
              --startUrl ${{secrets.GI_START_URL}} || errors=$((errors+1)) 

          # Após o loop, falha o job se houver erros
          if [ $errors -gt 0 ]; then
            echo "$errors teste(s) falharam."
            exit 1  # Falha o workflow
          else
            echo "Todos os testes passaram!"
          fi