name: Ghost Inspector Tests

on:
  push:
    branches: [main]
  


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Ghost Inspector CLI e capturar saída
        run: |
          docker run ghostinspector/cli suite list --apiKey ${{ secrets.GI_API_KEY }} --json | jq '.[]._id' > output.json

      - name: Executar testes para cada ID extraído
        run: |
          for suite_id in $(cat output.json); do
            echo "Executando teste para a suíte ID: $suite_id"
            docker run ghostinspector/cli suite execute $suite_id \
              --apiKey ${{ secrets.GI_API_KEY }} \
              --startUrl https://staging.clint.digital \
              --errorOnFail
          done
            