name: Ghost Inspector Tests

on:
  workflow_run:
    workflows: [teste-wait]
    types: [completed]

jobs:
  wait-for-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Esperar outras actions
        run: echo "Aguardando outras actions finalizarem..."

  test:
    runs-on: self-hosted
    needs: wait-for-actions
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4

      - name: Run Ghost Inspector CLI and get output
        run: |
          docker run --rm ghostinspector/cli suite list --apiKey ${{ secrets.GI_API_KEY }} --json | jq '.[]._id' > output.json

      - name: Run tests for each ID
        run: |
          errors=0
          
          for suite_id in $(cat output.json); do
            if [ "$suite_id" = "\"6761d7427a599a5bc844ad51\"" ]; then
              echo "Ignore suíte ID: $suite_id"
              continue
            fi

            echo "Run tests ID: $suite_id"
            docker run --rm ghostinspector/cli suite execute $suite_id \
              --apiKey ${{ secrets.GI_API_KEY }} \
              --startUrl ${{ vars.GI_START_URL }}  --errorOnFail || errors=$((errors+1)) 
          done

          if [ $errors -gt 0 ]; then
            echo "😰 $errors test(s) that have failed."
            exit 1
          else
            echo "✅ All tests passed!"
          fi