name: Ghost Inspector Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mock test suite IDs
        run: |
           echo -e "674871a884d2a5c4a5b35b1e\n66f08c13437cb0e9bf903e4d" > output.json

      - name: Run tests for each ID
        run: |
            errors=0
            
            for suite_id in $(cat output.json); do
              echo "Running tests for ID: $suite_id"
              
              # Execute test and capture result as JSON
              result=$(docker run ghostinspector/cli suite execute $suite_id \
                --apiKey ${{ secrets.GI_API_KEY }} \
                --startUrl ${{ vars.GI_START_URL }} --json)

              # Capture and save the result
              echo "$result" > "result_$suite_id.json"
              
            done  

            echo "✅ All test results saved!"